package lsr.paxos.replica;

/**
 * Simple implementation of {@link IdGenerator} which is based on long numbers.
 * Id's generated by this class create sequence of consecutive long numbers. It
 * is possible to define first number in this sequence and the difference
 * between consecutive numbers.
 * 
 */

@Deprecated
public class SimpleIdGenerator implements IdGenerator {
	private Long _current;
	private final Long _step;

	/**
	 * Initialize new instance of <code>SimpleIdGenerator</code>.
	 * 
	 * @param start
	 *            - first number in generated sequence
	 * @param step
	 *            - difference between next's id's
	 * 
	 */
	public SimpleIdGenerator(long start, long step) {
		_current = start;
		_step = step;
	}

	/**
	 * Generates next number from the sequence specified by this generator.
	 * 
	 * This method is thread-safe.
	 * 
	 * @return next unique number
	 */
	public synchronized long next() {
		long res = _current;
		_current += _step;
		return res;
	}
}
